### ISSUE TITLE
Directory with "extension" breaks build production

### ISSUE THREAD

**Issue by bramstein** [assetgraph/assetgraph-builder#143]
Place the following file in a directory called `lettering.js` and run buildProduction.

```
<html>
  <body>
    <a href="/lettering.js/">Myself</a>
  </body>
</html>
```

`buildProduction --root . --outroot ./build/ lettering.js/index.html`

Output is:

```
 ✔ 0.001 secs: logEvents
 ✔ 0.001 secs: registerRequireJsConfig
 ✔ 0.002 secs: registerLabelsAsCustomProtocols
 ✔ 0.037 secs: loadAssets
 ✔ 0.004 secs: populate
 ✔ 0.000 secs: assumeRequireJsConfigHasBeenFound

/Users/bs/Projects/assetgraph-js-dir/node_modules/assetgraph-builder/node_modules/assetgraph/lib/resolvers/file.js:26
                                url: assetConfig.url.replace(/(\/)?((?:[?#].*$
                                                     ^
TypeError: Cannot call method 'replace' of undefined
  at /Users/bs/Projects/assetgraph-js-dir/node_modules/assetgraph-builder/node_modules/assetgraph/lib/resolvers/file.js:26:54
  at /Users/bs/Projects/assetgraph-js-dir/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/passerror/lib/passError.js:23:33
  at fs.js:266:14
  at Object.oncomplete (fs.js:107:15)
```

It seems to be interpreting the directory as a JS asset.

**Comment by papandreou** [comment]
Should be fixed now with https://github.com/assetgraph/assetgraph/pull/755

**Comment by bramstein** [comment]
🎉
