### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by abhirathore2006** [assetgraph/assetgraph-builder#689]
i am trying to upgrade the assetgraph-builder from 4.12.2 to 6.10.2 , i was able to create the bundle but i18n translation was not working, i tried the same on i18n example in test data and it is also failing. 

if i skip the static url of i18n  in below mentioned example then it doesn't translates the JavaScript code and i get TR not defined Error. 

```https://github.com/assetgraph/assetgraph-i18n/tree/master/testdata/transforms/checkLanguageKeys/duplicateLanguageKeys```

can you please provide an example for i18n translation with  assetgraph-i18n plugin

**Command** 
```node bin/buildProduction --root testdata/transforms/buildProduction/htmlDataMainWithI18n -o dist --plugin assetgraph-i18n --condition locale=en,da  --splitcondition locale testdata/transforms/buildProduction/htmlDataMainWithI18n/index.html```

```/home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph/lib/relations/JavaScriptStaticUrl.js:33
    throw new Error('Not implemented');
    ^

Error: Not implemented
    at JavaScriptStaticUrl.detach (/home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph/lib/relations/JavaScriptStaticUrl.js:33:11)
    at /home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph-i18n/lib/index.js:59:22
    at Array.forEach (<anonymous>)
    at AssetGraph.<anonymous> (/home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph-i18n/lib/index.js:58:12)
    at emitTwo (events.js:131:20)
    at AssetGraph.emit (events.js:214:7)
    at done (/home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph/lib/AssetGraph.js:632:12)
    at Immediate.setImmediate [as _onImmediate] (/home/abhimanyus/work/assetgraph-builder/node_modules/assetgraph/lib/AssetGraph.js:649:11)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)```

**Comment by papandreou** [comment]
Thanks for reporting this! I put in a band-aid in https://github.com/assetgraph/assetgraph-i18n/commit/0871b4b0c856aea0b6649eadd976769afdc90223 and released assetgraph-i18n 0.7.3.

Please see if that helps :)
